### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by masyoka** [ElementsProject/nanopos#1]
Please guys, some one help me to install on centos 7.
@tbr_kz

**Comment by shesek** [comment]
Are the instructions on the README not working? What issues are you running into?

**Comment by masyoka** [comment]
localhost:9016
But i need to show at my domain.com/nanopos/ hire to do that?

**Comment by shesek** [comment]
Do you already have an HTTP server running on your domain.com? If so, which one?

**Comment by masyoka** [comment]
Yes https://mydomain.me

**Comment by shesek** [comment]
I meant which HTTP server software

**Comment by masyoka** [comment]
Apache

**Comment by shesek** [comment]
You'll need to setup a reverse proxy from your apache server to the nodejs server running on `localhost:9116`. See [this blog post for more instructions](http://blog.podrezo.com/making-node-js-work-with-apache/).
