### ISSUE TITLE
Additionally show invoice as text

### ISSUE THREAD

**Issue by jonasnick** [ElementsProject/nanopos#13]
Right now the invoice is only displayed as QR code but if you have to copy and paste the invoice or if you're using the Tor browser (which doesn't display the QR codes by default) you want to see the invoice as text string.

**Comment by shesek** [comment]
nanopos was originally purposed for brick-and-mortar stores where the device is operated on-premise by the merchant, not for remote access from the consumer's browser.

In this context, displaying the BOLT11 string didn't seem to make much sense. In some of the other lapps that are meant for remote access, like [lightning jukebox](https://github.com/ElementsProject/lightning-jukebox), the BOLT11 and a payment button are shown (you can also see a similar live UI at https://party.bitcoin.org.il/, though its in Hebrew).

![lightning jukebox screenshot](https://camo.githubusercontent.com/bc7df3a207acea9cebc935c8d221288d01abe38a/68747470733a2f2f692e696d6775722e636f6d2f70545a6b5a30482e706e67)

But seeing that nanopos is also being used for remote sales, I think that adding this as an option definitely makes sense. I'll look into that!

**Comment by shesek** [comment]
@jonasnick `npm install -g nanopos@0.1.4`, then `nanopos --show-bolt11 ...` :)

**Comment by jonasnick** [comment]
Very nice, thanks!
