### ISSUE TITLE
Would you like a logo? 

### ISSUE THREAD

**Issue by andrejcibik** [ElementsProject/nanopos#4]
Hi,
excelent work! Im a graphic designer and I would like to create a logo for nanopos. For free, no strings attached. 

Will you provide me some feedback if I create something? 

More of my contibutions to open source projects - https://busy.org/@andrejcibik

**Comment by normandmickey** [comment]
I forked nanopos to https://github.com/normandmickey/lightningpos .  If Element doesn't want a logo I could use one.

**Comment by shesek** [comment]
Hi @andrejcibik, sorry for the slow reply! Lost track with all the notifications I was receiving these last days :)

I appreciate your kind offer and think a logo would be sweet to have. Do you see it getting incorporated in the product itself, or just as part of the README etc?

Please note that I cannot guarantee the logo will be used, as this also depends on the folks at blockstream. If you're okay with that, I would love to see what you can come up with. Thanks and cheers!

**Comment by andrejcibik** [comment]
Hi. Ideally as a main logo of the service. If the app should become mainstream, it needs at least basic branding. 

Thats ok, just like the open source code, contribution can be accepted or not :)
