### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by JonnyMaK** [ElementsProject/nanopos#5]
I seem to be having a issue with npm install.

root@BTCPayServerVM:/home/elementsprojects/nanopos# npm install
root@BTCPayServerVM:/home/elementsprojects/nanopos# npm start

> nanopos@0.0.1 start /home/elementsprojects/nanopos
> ./start.sh

npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
root@BTCPayServerVM:/home/elementsprojects/nanopos# npm install
root@BTCPayServerVM:/home/elementsprojects/nanopos# npm start

> nanopos@0.0.1 start /home/elementsprojects/nanopos
> ./start.sh

npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by shesek** [comment]
Hi @JonnyMaK, this looks like it might be an error with your nodejs installation. Can you try running the two following commands from the nanopos directory and see if they work as expected?

    $ node -e 'console.log("works")'
    $ ./node_modules/.bin/babel-node -e 'console.log("works")'

If they do, can you please check and report your nodejs version too (via `$ node -v`)?

**Comment by JonnyMaK** [comment]
I figured it out. I needed to get curl to point at version 9
Then the install was fine.

There was also an issue with npm, so I reinstalled that with aptitude

**Comment by shesek** [comment]
Great! Glad to hear you worked this out.
