### ISSUE TITLE
Add option to display payment request in textual BOLT11 format?

### ISSUE THREAD

**Issue by shesek** [ElementsProject/nanopos#7]
`nanopos` is usually expected to be run on a tablet and presented to the customer for QR scanning, but showing the BOLT11 request too might be useful for some use-cases. Could be added as a toggleable option.

This could be shown similarly to how its done on the [Lightning Jukebox](https://github.com/ElementsProject/lightning-jukebox):

![jukebox screenshot](https://camo.githubusercontent.com/bc7df3a207acea9cebc935c8d221288d01abe38a/68747470733a2f2f692e696d6775722e636f6d2f70545a6b5a30482e706e67)

**Comment by ch4ot1c** [comment]
It is very important, imo, to present the plaintext version as well. QR codes aren't shareable using speech.

**Comment by shesek** [comment]
Implemented in c6abc17b60ee62d1a3bd9e4c24acac4339e6edb7.
